language: python
python:
    - "3.6"

cache: pip
install:
    -pip install -r requirements.txt
    -pip install python-coveralls
    -pip install pytest
    -pip install pytest-cov
    -pip install coveralls

services:
    - postgresql

before_script:
    - psql -c 'create database test_db;' -U postgres


script:
    - pytest --cov=app --cov-report term-missing

after_success:
    - coveralls
