
language: python
python:
    - "3.6"
cache: pip
install:
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
services:
    - postgresql
before_script:
    - psql -c 'create database wbtest;' -U postgres

script:
    - pytest --cov=app/

after_success:
    - coveralls
